apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: ecom
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  clusterIP: None

  selector:
    app.kubernetes.io/name: mongo

  ports:
    - name: mongo
      port: {{ .Values.database.service.port }}
      targetPort: mongo