{{- if .Values.appIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app-ingress
  labels:
    app.kubernetes.io/part-of: ecom
  annotations:
    {{- range $key, $value := .Values.appIngress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.appIngress.healthcheckPath | quote }}
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: "200"
    argocd.argoproj.io/sync-wave: "4"

spec:
  ingressClassName: {{ .Values.appIngress.className }}

  rules:
    - host: {{ .Values.appIngress.host }}
      http:
        paths:

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "ecom.backend.fullname" . }}-svc
                port:
                  number: {{ .Values.backend.service.port }}

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ecom.frontend.fullname" . }}-svc
                port:
                  number: {{ .Values.frontend.service.port }}

{{- end }}