apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.healthcheckPath }}
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.appHost }}
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend-svc
                port:
                  number: {{ .Values.backend.service.port }}

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend-svc
                port:
                  number: {{ .Values.backend.service.port }}

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-svc
                port:
                  number: {{ .Values.frontend.service.port }}