{{- if and .Values.platformIngress.enabled .Values.platformIngress.argocd.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-argocd-ingress
  namespace: {{ .Values.platformIngress.argocd.namespace }}
  annotations:
    {{- range $key, $value := .Values.appIngress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    argocd.argoproj.io/sync-wave: "4"

spec:
  ingressClassName: {{ .Values.appIngress.className }}

  rules:
    - host: {{ .Values.platformIngress.argocd.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.platformIngress.argocd.serviceName }}
                port:
                  number: {{ .Values.platformIngress.argocd.servicePort }}
{{- end }}