{{- if and .Values.platformIngress.enabled (or .Values.platformIngress.grafana.enabled .Values.platformIngress.prometheus.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-monitoring-ingress
  namespace: {{ .Values.platformIngress.grafana.namespace }}
  annotations:
    {{- range $key, $value := .Values.appIngress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: {{ .Values.appIngress.className }}
  rules:
    {{- if .Values.platformIngress.grafana.enabled }}
    - host: {{ .Values.platformIngress.grafana.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.platformIngress.grafana.serviceName }}
                port:
                  number: {{ .Values.platformIngress.grafana.servicePort }}
    {{- end }}

    {{- if .Values.platformIngress.prometheus.enabled }}
    - host: {{ .Values.platformIngress.prometheus.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.platformIngress.prometheus.serviceName }}
                port:
                  number: {{ .Values.platformIngress.prometheus.servicePort }}
    {{- end }}
{{- end }}