apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecom.backend.fullname" . }}-svc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}