apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom
  namespace: argocd
  labels:
    app.kubernetes.io/name: ecom
    app.kubernetes.io/part-of: ecom
    app.kubernetes.io/managed-by: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/akash66sheoran/ecom-gitops
    targetRevision: HEAD
    path: helm

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ecom

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5