frontend:
  replicas: 2
  containerPort: 80

  image:
    repository: 259974370560.dkr.ecr.ap-south-1.amazonaws.com/ecom-app/frontend
    tag: "153"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"

  livenessProbe:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 3

  readinessProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

backend:
  replicas: 2
  containerPort: 3000

  image:
    repository: 259974370560.dkr.ecr.ap-south-1.amazonaws.com/ecom-app/backend
    tag: "153"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000

  env:
    mongodbUri: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/app?replicaSet=rs0"
    port: "3000"

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

  livenessProbe:
    path: /health/live
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 3

  readinessProbe:
    path: /health/ready
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

database:
  replicas: 3
  containerPort: 27017

  image:
    repository: mongo
    tag: "4.2"
    pullPolicy: IfNotPresent

  replicaSetName: rs0
  wiredTigerCacheSizeGB: "0.1"

  service:
    port: 27017

  storageClass: gp3
  storage: 1Gi

  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

appIngress:
  enabled: true

  className: alb

  host: ecom.akashsheoran.in
  healthcheckPath: /health

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: ecom-alb
    alb.ingress.kubernetes.io/backend-protocol: HTTP

platformIngress:
  enabled: true

  argocd:
    enabled: true
    host: argocd.akashsheoran.in
    namespace: argocd
    serviceName: argocd-server
    servicePort: 80

  kibana:
    enabled: true
    host: kibana.akashsheoran.in
    namespace: observability
    serviceName: kibana-kb-http
    servicePort: 5601

  grafana:
    enabled: true
    host: grafana.akashsheoran.in
    namespace: monitoring
    serviceName: monitoring-grafana
    servicePort: 80

  prometheus:
    enabled: true
    host: prometheus.akashsheoran.in
    namespace: monitoring
    serviceName: monitoring-kube-prometheus-prometheus
    servicePort: 9090

secrets:
  enabled: true
  name: mongo-secret-provider
  mongoSecretName: "prod/ecom/mongodb-creds"